azs:
- cloud_properties:
    availability_zone: ap-northeast-1a
  name: z1
- cloud_properties:
    availability_zone: ap-northeast-1c
  name: z2
- cloud_properties:
    availability_zone: ap-northeast-1d
  name: z3
compilation:
  az: z1
  network: private
  reuse_compilation_vms: true
  vm_extensions:
  - 100GB_ephemeral_disk
  vm_type: c4.large
  workers: 6
disk_types:
- cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 1024
  name: default
- cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 1024
  name: 1GB
- cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 5120
  name: 5GB
- cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 10240
  name: 10GB
- cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 51200
  name: 50GB
- cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 102400
  name: 100GB
- cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 512000
  name: 500GB
- cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 1048576
  name: 1TB
networks:
- name: private
  subnets:
  - az: z1
    cloud_properties:
      security_groups:
      - sg-0fb85a4d27273db7c
      subnet: subnet-044c66505b913c5ab
    gateway: 10.0.16.1
    range: 10.0.16.0/20
    reserved:
    - 10.0.16.2-10.0.16.3
    - 10.0.31.255
    static:
    - 10.0.31.190-10.0.31.254
  - az: z2
    cloud_properties:
      security_groups:
      - sg-0fb85a4d27273db7c
      subnet: subnet-0c6ad2b6d67599787
    gateway: 10.0.32.1
    range: 10.0.32.0/20
    reserved:
    - 10.0.32.2-10.0.32.3
    - 10.0.47.255
    static:
    - 10.0.47.190-10.0.47.254
  - az: z3
    cloud_properties:
      security_groups:
      - sg-0fb85a4d27273db7c
      subnet: subnet-00c071857cae2d18c
    gateway: 10.0.48.1
    range: 10.0.48.0/20
    reserved:
    - 10.0.48.2-10.0.48.3
    - 10.0.63.255
    static:
    - 10.0.63.190-10.0.63.254
  type: manual
- name: default
  subnets:
  - az: z1
    cloud_properties:
      security_groups:
      - sg-0fb85a4d27273db7c
      subnet: subnet-044c66505b913c5ab
    gateway: 10.0.16.1
    range: 10.0.16.0/20
    reserved:
    - 10.0.16.2-10.0.16.3
    - 10.0.31.255
    static:
    - 10.0.31.190-10.0.31.254
  - az: z2
    cloud_properties:
      security_groups:
      - sg-0fb85a4d27273db7c
      subnet: subnet-0c6ad2b6d67599787
    gateway: 10.0.32.1
    range: 10.0.32.0/20
    reserved:
    - 10.0.32.2-10.0.32.3
    - 10.0.47.255
    static:
    - 10.0.47.190-10.0.47.254
  - az: z3
    cloud_properties:
      security_groups:
      - sg-0fb85a4d27273db7c
      subnet: subnet-00c071857cae2d18c
    gateway: 10.0.48.1
    range: 10.0.48.0/20
    reserved:
    - 10.0.48.2-10.0.48.3
    - 10.0.63.255
    static:
    - 10.0.63.190-10.0.63.254
  type: manual
vm_extensions:
- cloud_properties:
    ephemeral_disk:
      size: 1024
      type: gp2
  name: 1GB_ephemeral_disk
- cloud_properties:
    ephemeral_disk:
      size: 5120
      type: gp2
  name: 5GB_ephemeral_disk
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
  name: 10GB_ephemeral_disk
- cloud_properties:
    ephemeral_disk:
      size: 51200
      type: gp2
  name: 50GB_ephemeral_disk
- cloud_properties:
    ephemeral_disk:
      size: 102400
      type: gp2
  name: 100GB_ephemeral_disk
- cloud_properties:
    ephemeral_disk:
      size: 512000
      type: gp2
  name: 500GB_ephemeral_disk
- cloud_properties:
    ephemeral_disk:
      size: 1048576
      type: gp2
  name: 1TB_ephemeral_disk
- cloud_properties:
    lb_target_groups:
    - mz-concourse-concourse80
    - mz-concourse-concourse443
    - mz-concourse-concourse2222
    - mz-concourse-concourse8443
    - mz-concourse-concourse8844
    security_groups:
    - mz-concourse-concourse-lb-internal-security-group
    - sg-0fb85a4d27273db7c
  name: lb
vm_types:
- cloud_properties:
    ephemeral_disk:
      size: 102400
      type: gp2
    instance_type: m4.large
  name: disk_100G_type
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.large
  name: default
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.large
  name: minimal
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t2.small
  name: sharedcpu
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.large
  name: small
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: r4.xlarge
  name: small-highmem
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.xlarge
  name: medium
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.2xlarge
  name: large
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.4xlarge
  name: extra-large
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c4.large
  name: small-highcpu
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.large
  name: m4.large
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.xlarge
  name: m4.xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.2xlarge
  name: m4.2xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.4xlarge
  name: m4.4xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.10xlarge
  name: m4.10xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c4.large
  name: c4.large
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c4.xlarge
  name: c4.xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c4.2xlarge
  name: c4.2xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c4.4xlarge
  name: c4.4xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c4.8xlarge
  name: c4.8xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: r3.large
  name: r3.large
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: r3.xlarge
  name: r3.xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: r3.2xlarge
  name: r3.2xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: r3.4xlarge
  name: r3.4xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: r3.8xlarge
  name: r3.8xlarge
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t2.nano
  name: t2.nano
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t2.micro
  name: t2.micro
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t2.small
  name: t2.small
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t2.medium
  name: t2.medium
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t2.large
  name: t2.large
